#!/bin/bash
set -euo pipefail

# create-tenant.sh — Create a new tenant deployment from templates
# Usage: ./create-tenant.sh --tenant <name> --port-offset <number> [options]

SCRIPT_DIR="${SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

# Defaults
TENANT=""
PORT_OFFSET=""
DATA_DIR=""
IMAGE_TAG="latest"
DRY_RUN=false

usage() {
    cat <<'USAGE'
Usage: create-tenant.sh --tenant <name> --port-offset <number> [options]

Required:
  --tenant <name>          Tenant name (alphanumeric + hyphens)
  --port-offset <number>   Port offset for multi-tenant isolation (0, 100, 200, ...)

Optional:
  --data-dir <path>        Tenant data directory (default: ./data/<tenant>)
  --image-tag <tag>        Docker image tag (default: latest)
  --dry-run                Show what would be created without writing files
  --help                   Show this help message

Example:
  ./create-tenant.sh --tenant acme --port-offset 100
  ./create-tenant.sh --tenant acme --port-offset 100 --data-dir /srv/acme --dry-run
USAGE
}

die() { echo "ERROR: $*" >&2; exit 1; }

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --tenant)    TENANT="$2"; shift 2 ;;
        --port-offset) PORT_OFFSET="$2"; shift 2 ;;
        --data-dir)  DATA_DIR="$2"; shift 2 ;;
        --image-tag) IMAGE_TAG="$2"; shift 2 ;;
        --dry-run)   DRY_RUN=true; shift ;;
        --help|-h)   usage; exit 0 ;;
        *)           die "Unknown option: $1" ;;
    esac
done

# Validate required args
[[ -n "$TENANT" ]]      || die "--tenant is required"
[[ -n "$PORT_OFFSET" ]] || die "--port-offset is required"

# Validate tenant name (alphanumeric + hyphens)
[[ "$TENANT" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$ ]] \
    || die "Tenant name must be alphanumeric (hyphens allowed, not at start/end): $TENANT"

# Validate port offset is a non-negative integer
[[ "$PORT_OFFSET" =~ ^[0-9]+$ ]] \
    || die "Port offset must be a non-negative integer: $PORT_OFFSET"

# Set data dir default
DATA_DIR="${DATA_DIR:-./data/${TENANT}}"

# Directories
TENANTS_DIR="${SCRIPT_DIR}/tenants"
TENANT_DIR="${TENANTS_DIR}/${TENANT}"

# Compute ports
PORT_OFFSET_9999=$((9999 + PORT_OFFSET))
PORT_OFFSET_5173=$((5173 + PORT_OFFSET))
PORT_OFFSET_5174=$((5174 + PORT_OFFSET))
PORT_OFFSET_5175=$((5175 + PORT_OFFSET))
DEMO_PORT=$((8000 + PORT_OFFSET))

# --- Port conflict detection ---
check_port_conflicts() {
    local conflict_found=false
    for existing_env in "${TENANTS_DIR}"/*/".env" ; do
        [[ -f "$existing_env" ]] || continue
        local existing_tenant
        existing_tenant="$(dirname "$existing_env")"
        existing_tenant="$(basename "$existing_tenant")"
        # Skip self (idempotent re-run)
        [[ "$existing_tenant" == "$TENANT" ]] && continue

        local existing_offset
        existing_offset=$(grep -E '^PORT_OFFSET=' "$existing_env" | head -1 | cut -d= -f2)
        [[ -n "$existing_offset" ]] || continue

        if [[ "$existing_offset" == "$PORT_OFFSET" ]]; then
            echo "CONFLICT: tenant '$existing_tenant' already uses PORT_OFFSET=$existing_offset" >&2
            conflict_found=true
        fi
    done
    if $conflict_found; then
        die "Port conflict detected. Choose a different --port-offset."
    fi
}

check_port_conflicts

# --- Dry-run reporting ---
if $DRY_RUN; then
    echo "=== DRY RUN ==="
    echo "Tenant:       $TENANT"
    echo "Port offset:  $PORT_OFFSET"
    echo "Data dir:     $DATA_DIR"
    echo "Image tag:    $IMAGE_TAG"
    echo ""
    echo "Would create:"
    echo "  ${TENANT_DIR}/.env"
    echo "  ${TENANT_DIR}/docker-compose.yml"
    echo "  ${DATA_DIR}/"
    echo ""
    echo "Ports:"
    echo "  channel-server: $PORT_OFFSET_9999"
    echo "  autoservice:    $DEMO_PORT"
    echo "  customer-chat:  $PORT_OFFSET_5173"
    echo "  operator-console: $PORT_OFFSET_5174"
    echo "  admin-portal:   $PORT_OFFSET_5175"
    exit 0
fi

# --- Create directories ---
mkdir -p "$TENANT_DIR"
mkdir -p "$DATA_DIR"

# --- Export variables for envsubst ---
export TENANT PORT_OFFSET PORT_OFFSET_9999 PORT_OFFSET_5173 PORT_OFFSET_5174 PORT_OFFSET_5175
export DEMO_PORT
export ZCHAT_IMAGE="zchat/channel-server:${IMAGE_TAG}"
export CHANNEL_SERVER_URL="ws://channel-server:${PORT_OFFSET_9999}"
export TENANT_DATA_DIR="$DATA_DIR"
export ANTHROPIC_API_KEY=""

cat > "${TENANT_DIR}/.env" <<EOF
# AutoService tenant environment variables
# Generated by create-tenant.sh

# Tenant identity
TENANT=${TENANT}

# Port offset for multi-tenant isolation (0, 100, 200, ...)
PORT_OFFSET=${PORT_OFFSET}

# Computed ports (base + offset)
PORT_OFFSET_9999=${PORT_OFFSET_9999}
PORT_OFFSET_5173=${PORT_OFFSET_5173}
PORT_OFFSET_5174=${PORT_OFFSET_5174}
PORT_OFFSET_5175=${PORT_OFFSET_5175}
DEMO_PORT=${DEMO_PORT}

# zchat channel-server image
ZCHAT_IMAGE=${ZCHAT_IMAGE}

# Service connectivity
CHANNEL_SERVER_URL=${CHANNEL_SERVER_URL}

# Tenant data directory (host path)
TENANT_DATA_DIR=${TENANT_DATA_DIR}

# REQUIRED - no default
ANTHROPIC_API_KEY=
EOF

# --- Render docker-compose.yml ---
envsubst < "${SCRIPT_DIR}/docker-compose.tmpl.yaml" > "${TENANT_DIR}/docker-compose.yml"

# --- Summary ---
echo "=== Tenant created: $TENANT ==="
echo "  Config:    ${TENANT_DIR}/.env"
echo "  Compose:   ${TENANT_DIR}/docker-compose.yml"
echo "  Data dir:  ${DATA_DIR}/"
echo ""
echo "Ports:"
echo "  channel-server:   $PORT_OFFSET_9999"
echo "  autoservice:      $DEMO_PORT"
echo "  customer-chat:    $PORT_OFFSET_5173"
echo "  operator-console: $PORT_OFFSET_5174"
echo "  admin-portal:     $PORT_OFFSET_5175"
echo ""
echo "Next steps:"
echo "  1. Edit ${TENANT_DIR}/.env and set ANTHROPIC_API_KEY"
echo "  2. cd ${TENANT_DIR} && docker compose up -d"
